# docker-compose -f data-playground.yml up -d
version: "3.4"
services:

  service-a:
    build: src/services/ServiceA
    environment:
      SA_PASSWORD: "Password.123"
      ACCEPT_EULA: "Y"
    ports:
      - "5000:80"
    depends_on: 
      - service-b
    links: 
      - service-b

  service-b:
    build: src/services/ServiceB
    environment:
      SA_PASSWORD: "Password.123"
      ACCEPT_EULA: "Y"
    ports:
      - "6000:80"