# docker-compose -f data-playground.yml up -d
version: "3.4"
services:

  service-a:
    build: 
      dockerfile: services/ServiceA/Dockerfile
      context: .
    environment:
      service-b-url: "http://service-b"
    depends_on: 
      - service-b
    links: 
      - service-b

  service-b:
    build: 
      dockerfile: services/ServiceB/Dockerfile
      context: .
    ports:
      - 6000:80
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain the service will respond to
      - "traefik.http.routers.serviceB.rule=PathPrefix(`/serviceB`)"
      - "traefik.http.routers.serviceB.service=service-b-src"
  
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"