# docker-compose -f data-playground.yml up -d
version: "3.4"
services:

  service-a:
    build: 
      dockerfile: services/ServiceA/Dockerfile
      context: .
    environment:
      service-b-url: "http://service-b"
    ports:
      - "5000:80"
    depends_on: 
      - service-b
    links: 
      - service-b

  service-b:
    build: 
      dockerfile: services/ServiceB/Dockerfile
      context: .
    ports:
      - "6000:80"