
name: Docker Hub - Build images 

on:
  push:
    branches:
      - 'WebApi'
    paths:
    - '.github/workflows/docker-github-action.yml'
    - 'src/services/DotNetWebApi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        username: stvansolano
        image: aspnet-webapi
        unique-tag: ${{ github.sha }}
      run: |
        docker build -f src/DotNetWebApi/Dockerfile "src" -t $username/$image:v1
        echo 'Version:'
        echo $version
        echo 'Unique tag:'
        echo $unique-tag